{% set version = "1.1.29" %}

package:
  name: libxslt-static
  version: {{ version }}

source:
  fn: libxslt-{{ version }}.tar.gz
  url: ftp://xmlsoft.org/libxslt/libxslt-{{ version }}.tar.gz


build:
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
    - libxml2-static ==2.9.3

  run:
    - libxml2-static ==2.9.3

about:
  home: http://xmlsoft.org/XSLT/
  summary: The XSLT C library for GNOME
