{% set version = "7.50.3" %}

package:
  name: curl-static
  version: {{ version }}

source:
  fn: curl-{{ version }}.tar.gz
  url: http://curl.haxx.se/download/curl-{{ version }}.tar.gz
  md5: 870e16fd88a88b52e26a4f04dfc161db

build:
  number: 1
  features:
    - vc9              # [win and py27]
    - vc14             # [win and (py35 or py36)]

requirements:
  build:
    - python           # [win]
    - vc 9             # [win and py27]
    - vc 14            # [win and (py35 or py36)]
    - gcc              # [linux]

  run:
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]

test:
  commands:
    - curl --version

about:
  home: http://curl.haxx.se
  summary: Curl is an open source command line tool and library for transferring data with URL syntax.
